
export const cnf = {
  URI_SERVER : import.meta.env.VITE_URL_DEVELOPMENT,
  ENDPOINT_LIBRO : import.meta.env.VITE_ENDPOINT_LIBRO,
  ENDPOINT_PRESTAMO : import.meta.env.VITE_ENDPOINT_PRESTAMO,
  ENDPOINT_AUTOR : import.meta.env.VITE_ENDPOINT_AUTOR,
  ENDPOINT_CATEGORIA : import.meta.env.VITE_ENDPOINT_CATEGORIA,
  ENDPOINT_AUTH : import.meta.env.VITE_ENDPOINT_AUTH,
}